# GitHub Sponsors configuration
# See: https://docs.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository

# Uncomment and update with your sponsor links if applicable:
# github: [your-username]
# patreon: your-username
# ko_fi: your-username
# custom: ["https://your-website.com/donate"]
