"""
VapourSynth script templates for advanced video processing.

This package contains .vpy script templates that can be used standalone
or programmatically generated by the VHS Upscaler pipeline.
"""

__all__ = []
