#!/usr/bin/env python3
"""
Generate sample LUT files for VHS Upscaler.

This script creates valid 33x33x33 3D LUT files in .cube format with
different color grading presets for VHS restoration.
"""

import math
from pathlib import Path


def generate_cube_lut(
    output_path: Path,
    transform_func,
    description: str,
    size: int = 33
):
    """
    Generate a 3D LUT in .cube format.

    Args:
        output_path: Output .cube file path
        transform_func: Function(r, g, b) -> (r', g', b') to transform colors
        description: Description comment for the LUT
        size: LUT size (default 33x33x33)
    """
    with open(output_path, 'w') as f:
        # Write header
        f.write(f"# {output_path.stem}\n")
        f.write(f"# {description}\n")
        f.write(f"# Generated by VHS Upscaler LUT Generator\n\n")
        f.write(f"LUT_3D_SIZE {size}\n\n")

        # Generate LUT entries
        # Iterate through all RGB values in the cube
        for b_idx in range(size):
            for g_idx in range(size):
                for r_idx in range(size):
                    # Normalize to 0.0-1.0
                    r = r_idx / (size - 1)
                    g = g_idx / (size - 1)
                    b = b_idx / (size - 1)

                    # Apply transformation
                    r_out, g_out, b_out = transform_func(r, g, b)

                    # Clamp to 0.0-1.0
                    r_out = max(0.0, min(1.0, r_out))
                    g_out = max(0.0, min(1.0, g_out))
                    b_out = max(0.0, min(1.0, b_out))

                    # Write entry
                    f.write(f"{r_out:.6f} {g_out:.6f} {b_out:.6f}\n")


def vhs_restore_transform(r: float, g: float, b: float) -> tuple:
    """
    VHS restoration color transform.

    Corrects typical VHS issues:
    - Slight blue channel boost (VHS tends to lose blue)
    - Saturation lift (VHS desaturates over time)
    - Slight contrast adjustment
    - Warm push to counteract VHS coolness
    """
    # Convert to working space
    # Lift shadows slightly
    r = r ** 0.95
    g = g ** 0.95
    b = b ** 0.95

    # Calculate luminance
    luma = 0.2126 * r + 0.7152 * g + 0.0722 * b

    # Boost saturation by 10%
    sat_boost = 1.10
    r = luma + (r - luma) * sat_boost
    g = luma + (g - luma) * sat_boost
    b = luma + (b - luma) * sat_boost

    # Warm push (slight red/yellow shift to counter VHS coolness)
    r = r * 1.02
    g = g * 1.01
    b = b * 0.98

    # Slight blue lift in shadows
    if luma < 0.3:
        b = b * 1.03

    return r, g, b


def warm_vintage_transform(r: float, g: float, b: float) -> tuple:
    """
    Warm vintage film look.

    Creates a warm, nostalgic film aesthetic:
    - Golden/amber color shift
    - Lifted blacks (faded look)
    - Reduced contrast
    - Slight desaturation in highlights
    """
    # Calculate luminance
    luma = 0.2126 * r + 0.7152 * g + 0.0722 * b

    # Lift blacks (fade effect)
    lift = 0.05
    r = r * (1 - lift) + lift
    g = g * (1 - lift) + lift
    b = b * (1 - lift) + lift

    # Warm color shift (orange/amber)
    r = r * 1.15
    g = g * 1.05
    b = b * 0.90

    # Reduce contrast slightly
    mid = 0.5
    r = mid + (r - mid) * 0.9
    g = mid + (g - mid) * 0.9
    b = mid + (b - mid) * 0.9

    # Desaturate highlights
    if luma > 0.7:
        desat_amount = (luma - 0.7) / 0.3  # 0 to 1
        r = luma + (r - luma) * (1 - desat_amount * 0.3)
        g = luma + (g - luma) * (1 - desat_amount * 0.3)
        b = luma + (b - luma) * (1 - desat_amount * 0.3)

    return r, g, b


def cool_modern_transform(r: float, g: float, b: float) -> tuple:
    """
    Cool modern clean look.

    Creates a clean, contemporary aesthetic:
    - Slight cool/teal shift
    - Crushed blacks (deep shadows)
    - Increased contrast
    - Boosted saturation in midtones
    """
    # Calculate luminance
    luma = 0.2126 * r + 0.7152 * g + 0.0722 * b

    # Crush blacks
    if luma < 0.1:
        crush_amount = (0.1 - luma) / 0.1
        r = r * (1 - crush_amount * 0.5)
        g = g * (1 - crush_amount * 0.5)
        b = b * (1 - crush_amount * 0.5)

    # Cool color shift (teal/cyan)
    r = r * 0.95
    g = g * 1.02
    b = b * 1.08

    # Increase contrast
    mid = 0.5
    r = mid + (r - mid) * 1.15
    g = mid + (g - mid) * 1.15
    b = mid + (b - mid) * 1.15

    # Boost saturation in midtones
    if 0.3 < luma < 0.7:
        sat_boost = 1.15
        r = luma + (r - luma) * sat_boost
        g = luma + (g - luma) * sat_boost
        b = luma + (b - luma) * sat_boost

    return r, g, b


def main():
    """Generate all sample LUTs."""
    # Create luts directory if it doesn't exist
    luts_dir = Path(__file__).parent.parent / "luts"
    luts_dir.mkdir(exist_ok=True)

    print("Generating sample LUT files...")
    print(f"Output directory: {luts_dir}")

    # Generate VHS restoration LUT
    print("\n1. Generating vhs_restore.cube...")
    generate_cube_lut(
        luts_dir / "vhs_restore.cube",
        vhs_restore_transform,
        "VHS color restoration - corrects blue shift and saturation loss"
    )
    print("   [OK] VHS restore LUT created")

    # Generate warm vintage LUT
    print("2. Generating warm_vintage.cube...")
    generate_cube_lut(
        luts_dir / "warm_vintage.cube",
        warm_vintage_transform,
        "Warm vintage film look - golden nostalgic aesthetic"
    )
    print("   [OK] Warm vintage LUT created")

    # Generate cool modern LUT
    print("3. Generating cool_modern.cube...")
    generate_cube_lut(
        luts_dir / "cool_modern.cube",
        cool_modern_transform,
        "Cool modern clean look - teal and orange Hollywood style"
    )
    print("   [OK] Cool modern LUT created")

    print("\n[OK] All LUT files generated successfully!")
    print(f"\nLUT files location: {luts_dir.absolute()}")
    print("\nUsage:")
    print("  vhs-upscale upscale video.mp4 -o output.mp4 --lut luts/vhs_restore.cube")
    print("  vhs-upscale upscale video.mp4 -o output.mp4 --lut luts/warm_vintage.cube --lut-strength 0.7")


if __name__ == "__main__":
    main()
